upstream platform_basic_service {
  server energy-platform-basic-service:8090;
}

upstream energy_log_service {
  server energy-log-service:8091;
}

server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html/portal;
  index index.html;

  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/xml;

  location /api/basic/actuator/ {
    proxy_pass http://platform_basic_service/actuator/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/logs/actuator/ {
    proxy_pass http://energy_log_service/actuator/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/basic/ {
    proxy_pass http://platform_basic_service/api/basic/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/platform/ {
    proxy_pass http://platform_basic_service/api/platform/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/logs/ {
    proxy_pass http://energy_log_service/api/logs/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /platform-admin/ {
    alias /usr/share/nginx/html/platform-admin/;
    try_files $uri =404;
  }

  location /basic-info/ {
    alias /usr/share/nginx/html/basic-info/;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
